version: 2.1
orbs:
  osv_scanner: ahmedmohamed2323/osv_scanner@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  osv_scanner:
    docker:
      - image: cimg/go:1.20.1
    environment:
      OSV_SCANNER_PLATFORM: linux
    steps:
      - osv_scanner/install
      - osv_scanner/osv

workflows:
  test-deploy:
    when: '\<< pipeline.job_status("osv_scanner") == "success" \>>'
    jobs:
      - osv_scanner:
          filters:
            tags:
              only: /.*/
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: ahmedmohamed2323/osv_scanner
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
# VS Code Extension Version: 1.4.0
