version: 2.1

orbs:
  osv-scanner:
    description: OSV scanner for container images
    parameters:
      image:
        type: string
        description: The container image to scan
        default: myimage:latest
    commands:
      scan:
        description: Scan the container image for vulnerabilities
        steps:
        - checkout
        - run:
              name: Scan container image
              command: |
                trivy --no-progress --format json -o results.json ${{ orb.osv-scanner.parameters.image }}
        - store_artifacts:
              path: results.json
              destination: scan-results
        - persist_to_workspace:
              root: .
              paths: scan-results

# VS Code Extension Version: 1.4.0
