version: 2.1
orbs:
  osv_scanner: ahmedmohamed2323/osv_scanner@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  osv_scanner:
    docker:
      - image: cimg/go:1.20.1
    steps:
      - checkout
      - run:
          name: Install Go 
          command: |
            sudo apt-get update && sudo apt-get install -y golang
      - run:
          name: Install OSV CLI 
          command: |
            go install github.com/google/osv-scanner/cmd/osv-scanner@v1
      - run: 
          name: Run osv_scanner 
          command: |
            ls
            osv-scanner -r .
      - run:
          name: Scan for OS Vulnerabilities 
          command: |
            osv-scanner/scan


workflows:
  test-deploy:
    jobs:
      - osv_scanner
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: ahmedmohamed2323/osv_scanner
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/


# VS Code Extension Version: 1.4.0
