version: 2.1
orbs:
  osv_scanner: ahmedmohamed2323/osv_scanner@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs!!
  # You may want to add additional validation steps to ensure the commands are working as expected.
  osv_scanner:
    docker:
        - image: cimg/go:1.20.1
    steps:
      - checkout
      - run:
          name: Install Go 
          command: |
            sudo apt-get update && sudo apt-get install -y golang
      - run:
          name: Install OSV CLI 
          command: |
            go install github.com/google/osv-scanner/cmd/osv-scanner@v1
      - run: 
          name: Run osv_scanner 
          command: |
            ls
            osv-scanner -r .
      - run:
          name: Scan for OS Vulnerabilities 
          command: |
            #GOPATH/bin/osv-scanner -- .
      - run: 
          name: Specify Lockfile(s)
          command: |
            osv-scanner --lockfile 'requirements.txt:/path/to/your/extra-requirements.txt'
  # Add a new job to run the integration test using the OSV Scanner orb
  integration-test:
    executor: osv_scanner/default
    steps:
      - checkout
      - osv_scanner/scan:
          path: .
          ignore_failures: false

workflows:
  test-deploy:
    jobs:
      - osv_scanner
      - integration-test:  # Add the integration test job to the workflow
          requires:
            - osv_scanner  # The integration test job depends on the osv_scanner job
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: ahmedmohamed2323/osv_scanner
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

# VS Code Extension Version: 1.4.0
