version: 2.1
orbs:
  osv_scanner: ahmedmohamed2323/osv_scanner@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  osv_scanner:
    #docker:
      #- image: cimg/go:1.20.1
    macos:
      xcode: "14.2.0"
    resource_class: macos.x86.medium.gen2
    steps:
      - checkout
      - osv_scanner/install
      - osv_scanner/osv
  
  osv_scanner_windows:
    machine:
      image: 'windows-server-2019-vs2019:2022.08.1'
      resource_class: windows.medium
      shell: powershell.exe -ExecutionPolicy Bypass
    steps:
      - run: osv_scanner_windows
  
workflows:
  test-deploy:
    when: '\<< pipeline.job_status("osv_scanner") == "success" \>>'
    jobs:
      - osv_scanner:
          filters:
            tags:
              only: /.*/
      - osv_scanner_windows:
          filters: 
            tags:
              only: /.*/
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: ahmedmohamed2323/osv_scanner
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
# VS Code Extension Version: 1.4.0
