version: 2.1
orbs:
  osv_scanner: ahmedmohamed2323/osv_scanner@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  osv-scanner:
    docker:
      - image: cimg/go:1.20.1
    steps:
      - osv-scanner/osv
      - run:
          name: Run osv and save output
          command: |
            osv scan --output-file osv_output.txt
      - run:
          name: Verify vulnerabilities were found
          command: |
            grep "Expected Vulnerability 1" osv_output.txt
            grep "Expected Vulnerability 2" osv_output.txt
      # ... additional test steps ...

workflows:
  test-deploy:
    when: '\<< pipeline.job_status("osv_scanner") == "success" \>>'
    jobs:
      - osv-scanner:
          filters:
            tags:
              only: /.*/
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: ahmedmohamed2323/osv_scanner
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/


# VS Code Extension Version: 1.4.0
