version: 2.1
orbs:
  osv_scanner: ahmedmohamed2323/osv_scanner@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  osv-scan:
    # Define a job that uses the osv_scanner orb
    executor: osv_scanner/default
    steps:
      - osv_scanner/scan:
          path: .

workflows:
  test-deploy:
    jobs:
      - osv-scan:
          # Apply the filters defined in the filters block to this job
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: ahmedmohamed2323/osv_scanner
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/



# VS Code Extension Version: 1.4.0
