version: 2.1

orbs:
  osv_scanner: ahmedmohamed2323/osv_scanner@dev:<<pipeline.git.revision>>

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Scan for OS vulnerabilities
          command: |
            osv scan --path /app
      # add more steps here

