description: >
  This command will echo .
# What will this command do?
# Descriptions should be short, simple, and clear.

version: 2.1

orbs:
  my-orb: ahmedmohamed2323/osv_scanner@1.2.4

jobs:
  my-job:
    steps:
      - my-orb/my-command:
          arg1: 'foo'
          arg2: 'bar'
